apex: False
debug: False
print_freq: 100
num_workers: 8
size: 256

epochs: 30
batch_size: 32


model_name: 'vit_small_patch16_256'

scheduler:
  name: 'CosineAnnealingLR'
  params: 
    T_max: 30
    eta_min: 1.0e-6

optimizer:
  name: AdamW
  use_sam: False
  params:
    lr: 1.0e-3
    weight_decay: 1.0e-2

loss_fn: BCEWithLogitsLoss

augmentation:
  transform:
    train:
      Resize:
        height: 256
        width: 256
      Transpose:
        p: 0.5
      VerticalFlip:
        p: 0.5
      HorizontalFlip:
        p: 0.5
      ShiftScaleRotate:
        p: 0.5
      GaussianBlur:
        p: 0.5
        sigma_limit: [0.1, 2.0]
      HueSaturationValue:
        hue_shift_limit: 0.2
        sat_shift_limit: 0.2
        val_shift_limit: 0.2
        p: 0.5
      RandomBrightnessContrast:
        brightness_limit: [-0.1, 0.1]
        contrast_limit: [-0.1, 0.1]
        p: 0.5
      ToGray:
        p: 0.5
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      # CoarseDropout:
      #   p: 0.2
      # Cutout:
      #   p: 0.2
      # ToTensorV2:
    valid:
      Resize:
        height: 256
        width: 256
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      # ToTensorV2:


  mixup:
    use: False
    alpha: 0.5

    
gradient_accumulation_steps: 1
max_grad_norm: 1000
seed: 42

target: label

n_fold: 3
trn_fold: [0, 1, 2]
